Use pathlib.Path instance.
mandiant/capa-testfiles pull request #193
Opened 2023-07-10 19:49 UTC by Aayush-Goel-04

Follows up [#1534](https://github.com/mandiant/capa/pull/1583) from capa

2023-07-10 20:08 UTC, williballenthin approved these changes

2023-07-11 08:25 UTC, williballenthin commented
looks like the filename check might behave differently now:

<img width="444" alt="image" src="https://github.com/mandiant/capa-testfiles/assets/156560/98137dee-d10a-4eea-8ff9-b4f9cdd96b5a">

see the CI failure

2023-07-11 08:27 UTC, williballenthin requested changes

2023-07-11 08:27 UTC, williballenthin commented on .github/check_sample_filenames.py
> +    for path in Path(args.testfiles).rglob("*"):
os.walk is recursive while rglob is not, so i think the behavior here is different and is causing the failures. 

if we need to keep os.walk around for the recursive behavior - thats ok.

2023-07-11 14:27 UTC, mr-tz commented on .github/check_sample_filenames.py
> +    for path in Path(args.testfiles).rglob("*"):
I think we also want to inspect sub directories...

2023-07-11 18:28 UTC, Aayush-Goel-04 commented on .github/check_sample_filenames.py
> +    for path in Path(args.testfiles).rglob("*"):
@williballenthin  @mr-tz  
Since rglob also creates path for sub-directories , I can add an if condition to check if path.is_dir then continue. Switching back to os.walk is also an option.

2023-07-11 19:43 UTC, Aayush-Goel-04 commented on .github/check_sample_filenames.py
> +    for path in Path(args.testfiles).rglob("*"):
Since we only want to process endpoint files I think os.walk is the best method for this case.

2023-07-12 06:38 UTC, mr-tz commented on .github/check_sample_filenames.py
> +    sys.exit(main())
```suggestion
    sys.exit(main())

```

2023-07-12 06:39 UTC, mr-tz approved these changes
LGTM

2023-07-12 09:08 UTC, williballenthin approved these changes
lgtm

thank you @Aayush-Goel-04!

2023-07-12 09:08 UTC, merged